Desktop
donice/Microverse-Portal-Capstone pull request #1
Opened 2023-08-02 14:05 UTC by donice

2023-08-02 21:59 UTC, andersonlebon requested changes
## Hi @donice 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Highlights 🍾 

- Nice design 👏  ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-02 21:59 UTC, andersonlebon commented on index.html
> +  </header>
- [ ]  As the design requires we should keep spacesisetween elements, kindly make sure the you use the same thing for your desketop menu items. Check this

Your design | the template
---|---
![image](https://github.com/donice/Microverse-Portal-Capstone/assets/65068771/66bbe240-7f9b-4b03-93fc-dc378ba4f645) | ![image](https://github.com/donice/Microverse-Portal-Capstone/assets/65068771/1e351731-9cd4-4595-94c9-e299cec095b3)

- [ ] I think there is a missing tob navigation bar, kindly add it as required in the design guidlines. 

![image](https://github.com/donice/Microverse-Portal-Capstone/assets/65068771/e897bff8-8ee5-45b1-bc4b-10b3d8f35b7f)

2023-08-02 21:59 UTC, andersonlebon commented on about.html
> +        </ul>
- [ ] KIndly provide the link to the home page in the about page navigation bar as required

2023-08-02 21:59 UTC, andersonlebon commented on about.html
> +          </p>
- [ ] KIndly make sure your design match with the template, this fist section should have a backgound image abd a transparent color.

- [ ] Remember that your project should have the same design as the template but you should presonalize you content with a good logic by choosing a topic different to the template one.

Your design | the template
---|---
![image](https://github.com/donice/Microverse-Portal-Capstone/assets/65068771/46b98c12-fd18-4dd7-9551-7323ea0804b4) | ![image](https://github.com/donice/Microverse-Portal-Capstone/assets/65068771/c414ad66-469c-49c7-bf76-a989dac0606b)

### Apply the same review to the About page

2023-08-03 04:16 UTC, Shedrack-Sunday approved these changes
Hi @donice 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of CSS features ✔️ 
- [x] Kudus on meeting the requirements suggested  ✔️


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-03 04:17 UTC, merged